### PR TITLE
Add pytest.ini default config + changes to .gitignore and .dockerignore

### PR DESCRIPTION
**Pull request by vlieven**
## What changes were proposed in this pull request?
This adds a default config file for pytest with some helpful defaults (pytest.ini).

## Why are the changes needed?
Using the importlib mechanism for test imports avoids errors when names conflict.
We are using this config to avoid weird errors popping up.

## How was this tested?
No tests added, as this is configuration

### CODE REVIEW

**Comment by oliverw1** [comment]
That means you're not having tests inside packages, am I right?

Regardless, I like this approach, seeing as how the pytest devs intend to make this mechanism the default. We might as well get used to it.

**Comment by vlieven** [comment]
Our tests have the structure as proposed by the Datafy templates, so tests are separate from application packages (which live inside the 'src' folder). But the tests folder is structured as packages (contains __init__.py).

**Comment by stijndehaes** [comment]
I don't have enough knowledge about this topic to chime in. If @oliverw1 and @vlieven agree this is a good thing to add I trust your judgement :) @oliverw1 can you formally approve that this is the right way to do things then I'll merge this PR!

**Comment by oliverw1** [comment]
@stijndehaes yes, [this makes sense](https://docs.pytest.org/en/6.2.x/pythonpath.html#import-modes) to me. I would request that @vlieven also adds the minimum constraint to pytest in the various requirements files (dev-requirements.in, Pipfile), to avoid ambiguous dependencies.

Do note that I find it puzzling that the setup of @vlieven, which is the default of datafy and uses a packaging structure in the tests folder, caused issues. I don't know the specifics of his project though. But the change proposed here is one that the pytest developers intend to make permanent anyway.

**Comment by stijndehaes** [comment]
@vlieven can you add the minimum constraint to pytest? Then we can merge this PR :)

**Comment by vlieven** [comment]
@stijndehaes Noticed that I forgot to follow up on this. Minimum constraints have been added now

**Pull request merged**
